---
server:
  port: 8080

spring:
  application:
    name: kt-authentication-api
  web:
    locale: en_US
    locale-resolver: fixed
  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

authentication:
  session-ttl: ${SESSION_TTL}
  issuer: ${ISSUER}
  access-token-ttl: ${ACCESS_TOKEN_TTL}
  access-token-secret: ${ACCESS_TOKEN_SECRET}
